apiVersion: v1
kind: Pod
metadata: 
    name: mypod
    labels: 
       app: 1stpod
spec:
    containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
